name: tardis-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - pillow
  - opencv
  - pip
  - pip:
      - ultralytics
      - torch
      - PySide6>=6.5
